### ISSUE TITLE
a mistake in document

### ISSUE THREAD

**Issue by PatchouliG** [dibyendumajumdar/ravi#162]
`Note that B and C operands need to have an extra bit compared to A. This is because B and A can reference registers or constants, and the extra bit is used to decide which one. But A always references registers so it doesn't need the extra bit.
`
"This is because B and A can reference " should be B and C

**Comment by dibyendumajumdar** [comment]
Thank you

**Comment by dibyendumajumdar** [comment]
Docs updated
