### ISSUE TITLE
embedding

### ISSUE THREAD

**Issue by cinterloper** [dibyendumajumdar/ravi#166]
is it possible to embed ravi in a c program, like you would with luajit?

**Comment by dibyendumajumdar** [comment]
Y of course

**Comment by cinterloper** [comment]
Is there an example of this?
The reason I ask is the terralang project is looking to replace luajit, and since this project is so similar, i wanted to try using it as the host lua runtime for the terra compiler.

**Comment by dibyendumajumdar** [comment]
Hi, I am not sure Ravi is a good replacement for LuaJIT .. LuaJIT can optimize standard Lua code, but Ravi needs type annotations for optimum code generation. Also LuaJIT has ffi which Ravi doesn't.

Re example of embedded use, you can look at https://github.com/redukti/OpenRedukti/blob/master/cpp/raviapi.cpp.

Its basically no different from standard Lua 5.3.

**Comment by cinterloper** [comment]
Got it. Thanks for the explanation.
