### ISSUE TITLE
automate tests with CI

### ISSUE THREAD

**Issue by starius** [dibyendumajumdar/ravi#18]
You are implementing opcodes and changing the code. Something can be accidentally  broken. Since Lua itself and Ravi have some tests, it worth using a continuous integration platform for this project.

You can use [lua-travis-example][1] as an example.

[1]: https://github.com/moteus/lua-travis-example

**Comment by dibyendumajumdar** [comment]
I run the tests manually before every check-in. Agree that continuous integration would be preferable - but I think it can wait until I get more people contributing to the code base. Right now with me as sole developer it is not so much of an issue

**Comment by starius** [comment]
Even for sole developer CI is helpful, because it runs independently on fresh machine. It helps to detect things like files forgotten to be commited. By the way Github reports 4 forks. CI can also test pull requests before they are merged. I think, it worth using CI.

**Comment by dibyendumajumdar** [comment]
Not disputing the usefulness of CI. And thanks for pointing me to travis-ci - I wasn't aware of it.

**Comment by dibyendumajumdar** [comment]
https://travis-ci.org/dibyendumajumdar/ravi
