### ISSUE TITLE
Do not hard-code the optimization level

### ISSUE THREAD

**Issue by romix** [dibyendumajumdar/ravi#19]
You currently seem to hardcode the LVVM optimization level:
```c++
llvm::PassManagerBuilder pmb;
pmb.OptLevel = 1;
pmb.SizeLevel = 0;
```

May be it is a good idea to provide a command-line parameter or some other means of configuring it?
Have you tried with OptLevel=2 or OptLevel=3? I can imagine that require more time for JITting, but may be they produce a much better code?

**Comment by dibyendumajumdar** [comment]
Yes I intend to add an API to set the optimization level. I have tested with OptLevel = 3 - it improves things slightly but not much. The issue is not with LLVM - just need to put more specialization of FOR loops.

**Comment by romix** [comment]
> The issue is not with LLVM 

Are you sure about it? May be you follow the Lua VM too closely? I.e. what if you can prove that certain concrete operations (or sequences of operations) being JITTed are not observable from Lua, i.e. only their return/result value is visible to Lua/C, but not how it was obtained. E.g. the computation of the return/result value cannot be interrupted and cannot escape into Lua/C land. In this case one could be much more aggressive about certain optimizations, now? E.g. one does not need to exactly mimic what Lua VM does for the same instruction (like updating the TValues, etc). It is probably possible to do more of copy propagations, load/store propagations, etc. If you can prove that the type does not change during this specific computation, you could use the type-specific version of operations, i.e. specialize. Or do you already do all this?

**Comment by dibyendumajumdar** [comment]
Well from  a performance point of view I think there are three areas of work:

a) How values are represented 
b) How for loops are implemented - Lua's forloop has to handle 4 different scenarios, and also requires updates to an extra index variable
c) Providing LLVM with correct metadata to allow it to perform accurate type based alias analysis

I have been too busy just implementing OP codes to look at a) or b). I have done some work on c) but not really validated that it is always correct.

**Comment by dibyendumajumdar** [comment]
Also to your point - although I follow Lua VM byte code - most op codes are generated as inline IR - exactly so that LLVM can perform its optimizations. So far I have found that without accurate metadata LLVM cannot do certain optimizations that require language level type information. Details here:

http://the-ravi-programming-language.readthedocs.org/en/latest/llvm-tbaa.html

**Comment by dibyendumajumdar** [comment]
Implemented API to set optimization level
