### ISSUE TITLE
FUNDING.yaml doesn't work

### ISSUE THREAD

**Issue by pfalcon** [dibyendumajumdar/ravi#190]
I don't know if you're noticed or not, But "Sponsor" button doesn't really work as expected (hopefully), the popup says:

> Some errors were encountered when parsing the FUNDING.yml file:
> 
>     Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
> 
> Learn more about formatting FUNDING.yml.
>

**Comment by dibyendumajumdar** [comment]
Hi I have removed the funding option as I cannot accept financial contributions at this time.
