### ISSUE TITLE
What kind of effort would be required to replace an embedded lua 5.3 with Ravi?

### ISSUE THREAD

**Issue by skunkiferous** [dibyendumajumdar/ravi#220]
The framework I'm interested in (Unreal Engine) has a Lua 5.3 plugin. The plugin is on the marketplace (commercially supported), but also open-source, so I assume it's "quality code".

If I wanted to use Ravi instead, would it be a "simple change" to modify the lua plugin, or is Ravi C interface sufficiently different that it would require a significant re-write of the plugin?

**Comment by dibyendumajumdar** [comment]
It should just work. If not please let me know

**Comment by skunkiferous** [comment]
Thanks. I'll contact you again, if I run into difficulties.
