### ISSUE TITLE
Add Ravi's intellisense to idea

### ISSUE THREAD

**Issue by aadog** [dibyendumajumdar/ravi#239]
Add Ravi's intellisense to idea

**Comment by dibyendumajumdar** [comment]
hi, 
Please would you explain what you meant here? I am sorry I did not understand.
Regards

**Comment by a97077088** [comment]
Sorry, I thought it was a Chinese project, so I used Chinese

**Comment by a97077088** [comment]
What I want to say is, can it be supported by idea plug-ins, such as emmylua

**Comment by dibyendumajumdar** [comment]
Hi I am not familiar with emmylua, I currently have a plug-in for vscode
