### ISSUE TITLE
Lua parsing error 

### ISSUE THREAD

**Issue by mustime** [dibyendumajumdar/ravi#241]
Compiling the following code into bytecode:

```lua
local t = {}

function t:GetNumFromStr(strData, Substr: string)
    local iSubLen = #Substr
    local iCount = 0
    local temp1 = strData
    for i = 1, #strData, 1 do
        local temp2 = string.sub(temp1, i, i + iSubLen - 1)
        if temp2 == Substr then
            i = i + iSubLen
            iCount = iCount + 1
        end
    end

    return iCount
end
```

and will end up with an error:

```
test.lua:11: Invalid assignment: integer expected near 'iCount'
```

However, if I change line: 4 to `local iSubLen: integer = #Substr`, it will get passed.

So I wonder doesn't `#` operation make `iSubLen` an integer already? Why `: integer` is needed.

**Comment by dibyendumajumdar** [comment]
hi
the # operator is not guaranteed to return an integer value as you have set meta method to override the behavior.

**Comment by XmiliaH** [comment]
@mustime I do not know what you do with `i = i + iSubLen` as
```lua
for i = 1, 10 do
    print(i)
    i = i + 2
end
```
might not give the result you expected.

**Comment by mustime** [comment]
> @mustime I do not know what you do with `i = i + iSubLen` as
> 
> ```lua
> for i = 1, 10 do
>     print(i)
>     i = i + 2
> end
> ```
> 
> might not give the result you expected.

Well, the logic I list above had been stripped down and somehow pointless. Just try to explain the case. And it seems only happened within the for-statement.

To make this simpler, try the following code: 
```
function foo(a, b)
    local x = #b
    for i = 1, #a, 1 do
        i = i + x
    end
end
```

And will get `test.lua: 5: Invalid assignment: integer expected near 'end'`
