### ISSUE TITLE
Some AOT Issues.

### ISSUE THREAD

**Issue by An0nyMooUS** [dibyendumajumdar/ravi#244]
I really liked this AOT system, I intend to use it in my project.

For this, I will collaborate with some issues that I am discovering :)

```
function test()
  
  local myPlayer = getMyPlayer()
  
  -- if ( myPlayer:Alive() ) then <-- fail (Unexpected pseudo: T(0[0..]))
  -- if ( myPlayer:Alive() == true (or expression like (number, string))) ) then <-- works 

  if ( myPlayer:Alive() == true ) then -- works
  
  end 
  
end
```
- Unexpected pseudo: T(0[0..]) on ``if`` expression. (maybe cannot determine bool value 🤔 )
- On large files ``assert(reg < MAXBIT);`` failed. ``pseudo_gen_free(PseudoGenerator *generator, unsigned reg)``

**Comment by dibyendumajumdar** [comment]
Okay thank you for the report - I will look at what's happening.

**Comment by dibyendumajumdar** [comment]
I couldn't reproduce the issue.

This test works

```
function test()
  local myPlayer = getMyPlayer()
  if ( myPlayer:Alive() ) then
    return true
  end
  return false
end

function getMyPlayer()
    local player = {}
    function player:Alive()
        print 'called'
        return true
    end
    return player
end

assert(test())
```

Perhaps you get the failure in a wider context?

**Comment by dibyendumajumdar** [comment]
hi @An0nyMooUS  I fixed the first issue.
Re the second issue, I will need to have a look at a test case I can try out - hope you are able to provide.

Thank you for the bug report

**Comment by An0nyMooUS** [comment]
> Unexpected pseudo:

```
if test:GetIsRight() then -- only works if ``== true`` explicitly.
   -- emit_op_cbr: Unexpected pseudo: T(1..)
end
```
