### ISSUE TITLE
Outdated JIT information

### ISSUE THREAD

**Issue by jserv** [dibyendumajumdar/ravi#247]
Documentation [Ravi Performance Benchmarks](https://github.com/dibyendumajumdar/ravi/blob/master/readthedocs/ravi-benchmarks.rst) and [Ravi JIT Compilation Status](https://github.com/dibyendumajumdar/ravi/blob/master/readthedocs/ravi-jit-status.rst) are considered as outdated since Ravi switches to MIR as the base of JIT compilation rather than LLVM. The pages should be revised for latest JIT performance comparisons.

**Comment by dibyendumajumdar** [comment]
Thank you , yes those pages need an update

**Comment by dibyendumajumdar** [comment]
those docs are deleted.
