### ISSUE TITLE
make install overwrites headers of lua

### ISSUE THREAD

**Issue by starius** [dibyendumajumdar/ravi#66]
The following files from lua package are overwritten by ravi:

  * include/lua.h
  * include/luaconf.h
  * include/lualib.h

Can you install ravi headers to directory `include/ravi/`?

**Comment by dibyendumajumdar** [comment]
I have been adopting the deployment strategy of putting all ravi components in a dedicated location, rather than the system locations. I assume you tried installing using the system locations?

How do you handle different Lua versions? Are they installed in different locations?

**Comment by starius** [comment]
> How do you handle different Lua versions? Are they installed in different locations?

Actually, I am trying to cross-compile ravi from Linux to Windows using [MXE](http://mxe.cc). Lua is already cross-compiled and installed to `include/lua.h` (and LuaJIT to `include/luajit-2.0/lua.h`). Maybe Lua should be installed to `include/lua-5.3/lua.h` instead, but it is unrelated issue.

**Comment by dibyendumajumdar** [comment]
Resolved in repository
