### ISSUE TITLE
LLVM 3.4 is not usable

### ISSUE THREAD

**Issue by starius** [dibyendumajumdar/ravi#67]
I failed to compile Ravi with llvm 3.4:

```
-- Found LLVM 3.4svn
-- Using LLVMConfig.cmake in: .../share/llvm/cmake
CMake Error at CMakeLists.txt:167 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".


-- Configuring incomplete, errors occurred!
```

**Comment by dibyendumajumdar** [comment]
Hi - unfortunately LLVM 3.4 is not supported. These days I am only testing with 3.7. 3.5 and 3.6 should still work but lately haven't been tested.

Note that some of the LLVM distros are broken so better to build it from source.
