### ISSUE TITLE
.dll.a library is installed to bin/ instead of lib/

### ISSUE THREAD

**Issue by starius** [dibyendumajumdar/ravi#68]
Ravi installs the following files:
  * bin/libravi.dll
  * bin/libravi.dll.a

Instead it should install bin/libravi.dll and **lib**/libravi.dll.a.

In CMakeLists.txt:
```
install(TARGETS ravi lua
        DESTINATION bin)
```

**Comment by dibyendumajumdar** [comment]
Thanks for the feedback - makes sense

**Comment by dibyendumajumdar** [comment]
Fixed in 0.12
