### ISSUE TITLE
How to build static ravi?

### ISSUE THREAD

**Issue by starius** [dibyendumajumdar/ravi#70]
I want `libravi.a` in addition to `libravi.dll` and `libravi.dll.a`.
Please add cmake option for static build.

**Comment by dibyendumajumdar** [comment]
Would this be an option or did you want both static and shared versions built?

**Comment by starius** [comment]
Two independent options would be better:

  * whether to build static
  * whether to build shared

**Comment by dibyendumajumdar** [comment]
Resolved in 0.17
