### ISSUE TITLE
Fix build on travis-ci

### ISSUE THREAD

**Issue by dibyendumajumdar** [dibyendumajumdar/ravi#87]
The build on travis-ci is failing with following error:

$ curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -
gpg: no valid OpenPGP data found.
The command "curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -" failed and exited with 2 during .

**Comment by jadr2ddude** [comment]
It works now. The LLVM apt repository was down (see [this](https://github.com/travis-ci/travis-ci/issues/6217)). But now it is up and running again. My PR #90 Travis build worked.

**Comment by dibyendumajumdar** [comment]
Yes thank you.
