### ISSUE TITLE
Add support for 32 bit integer and number on 32-bit systems

### ISSUE THREAD

**Issue by jadr2ddude** [dibyendumajumdar/ravi#89]
I am working on a project where I am working with 32-bit single board computers and am going to use ravi. It would be more efficient to use 32-bit numbers for this.

Note: I started working on this. Will send in a pull request once it works.

**Comment by dibyendumajumdar** [comment]
Hi - in Lua 5.3 we have integer or double values. Doubles are obviously always 64-bit, did you mean that on 32-bit machines integers should be 32-bit?

Regards

**Comment by jadr2ddude** [comment]
The integers should be 32 bit, but the number type could also be 32 bit (float instead of double). Float would be faster on 32-bit ARM systems (think Raspberry Pi 2). Yes, I know this is not what Lua has as standard, but it would give much more efficiency for this type of stuff.

Even if you don't want float, the 32-bit int should probably be put in.

**Comment by dibyendumajumdar** [comment]
Adding an option to switch from 64-bit integer to 32-bit integer is something I would like to do. It should not be too hard I think. But I don't know when I will get time to do this.

**Comment by jadr2ddude** [comment]
I started it. I can put up what I have so far later today.

**Comment by jadr2ddude** [comment]
Actually, I think I am almost done. I will just put it in a pull request when I am done

**Comment by jadr2ddude** [comment]
My attempt is here: https://github.com/jadr2ddude/ravi
I am currently having trouble getting cmake to link with 32-bit llvm

**Comment by dibyendumajumdar** [comment]
Have you looked at https://github.com/dibyendumajumdar/ravi/blob/master/build-utils/cmake-32bit-llvm.bat

I build against 32-bit LLVM on Windows successfully.

**Comment by jadr2ddude** [comment]
I am using linux. It keeps using /usr/lib and I am trying to get it to use /usr/lib32. I have set every variable I could think of to the 32-bit version.

**Comment by jadr2ddude** [comment]
It works 32-bit with no JIT, so I am going to put in a pull request. Probably cmake just not wanting to link.

**Comment by dibyendumajumdar** [comment]
I have created a new branch to work on this. I will manually merge the changes as the pull request is against master. Will take me some time to validate all scenarios and ensure everything is correct. I only have about half a day per week to work on Ravi related issues, so this will take a few weeks to finish off.

**Comment by dibyendumajumdar** [comment]
@jadr2ddude  I have checked in a version of the changes on branch support-32bit-number. So far I have only tested on Windows 10.

**Comment by jadr2ddude** [comment]
Ok. If you want, I can add 32-bit tests to travis-ci

**Comment by dibyendumajumdar** [comment]
That would be great, many thanks!

**Comment by dibyendumajumdar** [comment]
Resolved in 0.17
