### ISSUE TITLE
Binary File IO

### ISSUE THREAD

**Issue by kappe-c** [dibyendumajumdar/ravi#91]
Hello, 
I like this project a lot because it adds speed when working with large arrays of numbers to the otherwise pretty perfect Lua (and like so many I'm frustrated with Luajit not movig on to Lua 5.3).
But there is one thing that I currently miss in Ravi and that is reading and writing binary data from files, for loading and saving all those numbers in a fast and accurate way.
In Lua I would use the C API for this or the FFI in Luajit but as far as I know all that does not work yet for Ravi.
Maybe one could extend the io.read function for this? I mean sth. analogous to fh:read( x ) where x='n' reads a number from a sequence of certain ascii characters. Then I would like to have implementations for x='i8', x='u8', ..., x='u64', x='f32' and x='f64' for the basic (unsigned) integer and float data types. Probably the (input) endiannes would have to be specified by the programmer, too (maybe as additional argument to io.open( filePath, 'rwb' ).

**Comment by dibyendumajumdar** [comment]
Hi, you can directly access the raw data in a number[] array from C code using the api function:

/* Get the raw data associated with the number array at idx.
 * Note that Ravi arrays have an extra element at offset 0 - this
 * function returns a pointer to &data[0] - bear in mind that
 */
LUA_API lua_Number *ravi_get_number_array_rawdata(lua_State *L, int idx);

Of course this needs to be used with care, as you should not overwrite memory beyond the allocated size.

**Comment by kappe-c** [comment]
Oh that's great! Thanks. Could you point me to where I can find documentation like this? I only see the basic readme and a lot of notes about llvm …
Is there an analogous function to get such data from C to Ravi? Like maybe ravi_set_number_array_rawdata ?

**Comment by dibyendumajumdar** [comment]
API additions are in lua.h file.

You get access to the actual raw array data so you can set the values directly by amending the array. Be careful that you don't cause memory crashes though - the length of the array can be obtained by using the normal Lua function for getting table length. Maybe I should amend the API to return also the end point of the array?

I haven't exposed a similar API for integer[] arrays yet.

**Comment by kappe-c** [comment]
> Maybe I should amend the API to return also the end point of the array?

That's not a must. If one can get the length as you described, it's fine for me.

> I haven't exposed a similar API for integer[] arrays yet.

I would very much appreciate that :-)

**Comment by dibyendumajumdar** [comment]
ravi_get_number_array_rawdata() api changed so that it also returns the length of the array data
Added ravi_get_integer_array_rawdata().

**Comment by dibyendumajumdar** [comment]
Have added additional API for integer arrays in 0.17
