### ISSUE TITLE
Error in LuaPosix about not enough registers

### ISSUE THREAD

**Issue by raingloom** [dibyendumajumdar/ravi#97]
I'm currently just playing around with Ravi on Arch Linux and checking what modules work with it, however, the error I ran into was not actually in a binary module, but one of its Lua parts.

Here is the command I ran:
```sh
$ ravi -l fixravi -l socket -l lfs -l posix |& clipxflood #fixravi is just for setting the package search paths from /usr/local to /usr
ravi: error loading module 'posix.deprecated' from file '/usr/share/lua/5.3/posix/deprecated.lua':
	/usr/share/lua/5.3/posix/deprecated.lua:878: function or expression needs too many registers near 'then'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/share/lua/5.3/posix/init.lua:40: in main chunk
	[C]: in function 'require'
	[C]: in ?
```
Just to be sure, I tested with Lua 5.3 and it worked. I haven't tested if the modules are functional, just whether they load or not.

**Comment by dibyendumajumdar** [comment]
Hi, this is probably because in Ravi the maximum number of local variables is 120, compared to about 250 in Lua 5.3. This is because Ravi's bytecode structure requires more space, the number of bits available to hold register numbers is redued. Details are on the main page.

**Comment by raingloom** [comment]
So I guess this is a non-issue then? Or is there planned to be work in this area?

In eithe case, I'll close this issue to decrease noise.
